version: '3.8'
services:
  app:
    image: bakare007/master:1.9
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=user 
      - DB_PASSWORD=password 
      - DB_NAME=mydb 
      - DB_PORT=5432
    depends_on:
      - db
    restart: on-failure
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=useryouruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      -pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  pgdata: